### ISSUE TITLE
multithreaded system waits in game thread

### ISSUE THREAD

**Issue by DitJee** [Reddy-dev/Unreal-Flecs#21]
**Descriptions**
I use some parts of the code from `FlecsWorld.h` that I believe are necessary to run multithreaded systems.

```cpp
struct FFlecsRunnableThreadWrapper final : public FRunnable
{
    ...
}

struct FFlecsThread
{
    ...
}

struct FFlecsTask
{
    ....
}

struct FOSApiInitializer
{
    ....
}
```

before going any further, I would like to point out that I made some changes to `os_api.cond_wait_` since there was a mutex locking error. I fixed it by unlocking the mutex before attempting to lock it again.

```cpp
os_api.cond_wait_ = [](ecs_os_cond_t Cond, ecs_os_mutex_t Mutex)
{
	std::condition_variable* Event = reinterpret_cast<std::condition_variable*>(Cond);
	std::mutex* MutexPtr = reinterpret_cast<std::mutex*>(Mutex);

        // my unlock addition
	MutexPtr->unlock();

	std::unique_lock Lock(*MutexPtr);
	Event->wait(Lock);
};
```

Lastly, I create a world and a system as shown here
```cpp
FlecsWorld = new flecs::world(1, &argv);
OSApiInitializer.InitializeOSAPI();
FlecsWorld->set_target_fps(60);
FlecsWorld->set_threads(12);

...

FlecsWorld.system<
   ...
>("ticking")
.multi_threaded()
.interval(1.0f)
.each([](
   ...
)
{
    ...
};
```

The results are shown in the graph.

![image](https://github.com/user-attachments/assets/740fdb61-b31e-462f-9160-9b3ff2d08697)

It can be seen that the game thread waits for all tasks to finish before moving on to the next tick. 
Is there any way to unblock the game thread?

**Comment by Reddy-dev** [comment]
Yep this is being fixed right now(just forgot to make an issue for this)

**Comment by Reddy-dev** [comment]
@DitJee Do you still have this?

**Comment by Reddy-dev** [comment]
On latest (should probably remove some of your changes as my push may override them)

**Comment by Reddy-dev** [comment]
@DitJee Oh also pretty sure the waiting is necessary in flecs's current multithreading impl, which i may expand upon soon
